setTimeout(()=>{
  document.getElementById('div').innerHTML=10
  setTimeout(()=>{
      document.getElementById('div').innerHTML=9
      setTimeout(()=>{
          document.getElementById('div').innerHTML=8
          setTimeout(()=>{
              document.getElementById('div').innerHTML=7
              setTimeout(()=>{
                  document.getElementById('div').innerHTML=6
                  setTimeout(()=>{
                      document.getElementById('div').innerHTML=5
                      setTimeout(()=>{
                          document.getElementById('div').innerHTML=4
                          setTimeout(()=>{
                              document.getElementById('div').innerHTML=3
                              setTimeout(()=>{
                                  document.getElementById('div').innerHTML=2
                                  setTimeout(()=>{
                                      document.getElementById('div').innerHTML=1
                                      setTimeout(()=>{
                                          document.getElementById('div').innerHTML="Happy Independence Day"
                                      },1000)    
                                  },1000);
                              },1000);
                          },1000);
                      },1000);
                  },1000);
              },1000);
          },1000);
      },1000);
  },1000); 
},1000);                               
